"=====VIMrc======
"Luke McAuley
let mapleader = " "
set nocompatible              " be iMproved, required
"===== Vundle Plugins =======
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
Plugin 'bling/vim-airline'
Plugin 'edkolev/tmuxline.vim'
Plugin 'flazz/vim-colorschemes'
Plugin 'gorkunov/smartpairs.vim'
Plugin 'kien/ctrlp.vim'
Plugin 'klen/python-mode'
Plugin 'tpope/vim-fugitive.git'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-dispatch' 
Plugin 'tpope/vim-eunuch' 
Plugin 'Yggdroot/indentLine'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'jplaut/vim-arduino-ino'
Plugin 'leafgarland/typescript-vim'
Plugin 'jason0x43/vim-js-indent'
Plugin 'sudar/vim-arduino-syntax'
" Not used atm
"Plugin 'Valloric/YouCompleteMe'
"Plugin 'syntastic'
"Plugin 'godlygeek/tabular'
"Plugin 'jondkinney/dragvisuals.vim'

call vundle#end()            " required
filetype plugin indent on    " required

"=======End of Vundle stuff ====

"======Plugin settings ====
"dragvisuals.vim
 vmap <expr>  L        DVB_Drag('right')
 vmap <expr>  J        DVB_Drag('down')
 vmap <expr>  K        DVB_Drag('up')
 vmap <expr>  H        DVB_Drag('left')

"syntastic
let g:syntastic_python_pylint_args = '--load-plugins pylint_django' 

"ctrlp.vim
set runtimepath^=~/.vim/bundle/ctrlp.vim

"vim-airline
let g:airline_powerline_fonts = 1
let g:airline_theme='powerlineish'
let g:airline#extensions#tabline#enabled = 1

" syntastic
"let g:syntastic_mode_map = {"mode":"passive"}

"pymode
let g:pymode_folding = 0


""" Mappings
map <leader>k :bnext<Return>
map <leader>j :bprev<Return>
map <leader>d :bd<Return>
map <leader>. :@<Return>
map <leader>o zo
map <leader>O zO

nnoremap <silent> <leader>ch :set hlsearch!<CR>
nmap <Leader>f :set fdm=syntax<CR>
set pastetoggle=<F2>
"" Tabularize mappings
nmap <Leader>a= :Tabularize /^[^=]*\zs=
vmap <Leader>a= :Tabularize /^[^=]*\zs=
nmap <Leader>a: :Tabularize /:<CR>
vmap <Leader>a: :Tabularize /:<CR>
nmap <Leader>a:: :Tabularize /:\\zs<CR>
vmap <Leader>a:: :Tabularize /:\\zs<CR>
nmap <Leader>a, :Tabularize /,<CR>
vmap <Leader>a, :Tabularize /,<CR>
nmap <Leader>ac :Tabularize /\/\/<CR>
vmap <Leader>ac :Tabularize /\/\/,<CR>

"""TypescriptTools
""au BufRead,BufNewFile *.ts setlocal filetype=typescript
""set rtp+=/usr/local/lib/node_modules/typescript-tools

""" colorscheme
syntax on
colorscheme molokai
set t_Co=256

""" Tab settings
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab
"=====Search options
set hlsearch
set ignorecase
set smartcase

""" Misc
au FileType c,cpp setlocal comments-=:// comments+=f://
""set makeprg=gcc\ -o\ %<\ %
set wildmenu
set wildmode=longest:full,full
set laststatus=2
set confirm
set ruler
set number
set clipboard=unnamedplus
set hidden
set noswapfile
set nowrap
let loaded_matchparen = 1
"autocmd QuickFixCmdPost [^l]* nested cwindow
"autocmd QuickFixCmdPost    l* nested lwindow
